const data = [
  'Gospel means, simply, "good news." There are numerous so-called gospels in the world proclaiming good news to those who would listen, and these gospels come in any number of forms—from the gospel of wealth and power to the gospel of health and beauty. These gospels, however, do not address the most basic problem that all men and women have — the problem of sin and guilt; that is, spiritual deadness.',
  "Put simply, the Gospel is the good news of Jesus Christ. It is good news because, without it, we stand condemned as sinners before a holy and just God, deserving His wrath. In Isaiah's vision of the throne room of God, seraphim (angelic beings) cry out continually, \"Holy, holy, holy is the Lord of hosts; the whole earth is full of His glory!” Isaiah, overwhelmed in the presence of God, cries out in despair: “Woe is me! For I am lost; for I am a man of unclean lips, and I dwell in the midst of a people of unclean lips; for my eyes have seen the King, the Lord of hosts!” (Isa. 6:3, 5)",
  "Yet, in God's perfect holiness—and this is the good news—God has, in His good pleasure, made a way for sinners to be reconciled to Himself through His Son Jesus Christ. John 3:16-17 says, For God so loved the world, that He gave His only Son, that whoever believes in Him should not perish but have eternal life. For God did not send His Son into the world to condemn the world, but in order that the world might be saved through Him.",
  'Jesus Christ lived a righteous life and then died a terrible death on a Roman cross for His people. "All we like sheep have gone astray; we have turned—every one—to his own way; and the Lord has laid on Him the iniquity of us all" (Isa. 53:6). Thus, Jesus Christ satisfied the holy and just requirements of God. God then raised Him from the dead, vindicating Christ\'s work.',
  "Sinners are called to repent and believe the Gospel and to trust in Christ for salvation. Sinners receive this free gift of salvation from God through faith alone in Jesus Christ alone and are thereby counted righteous before God. Romans 10:9-13 states,",
  'If you confess with your mouth that Jesus is Lord and believe in your heart that God raised Him from the dead, you will be saved. For with the heart one believes and is justified, and with the mouth one confesses and is saved. For the Scripture says, "Everyone who believes in Him will not be put to shame." For there is no distinction between Jew and Greek; for the same Lord is Lord of all, bestowing His riches on all who call on Him. For "everyone who calls on the name of the Lord will be saved.',
  'Having been justified, Christians are called to walk as "living sacrifices" unto Him through the Holy Spirit because they are not their own, but were "bought with a price" (Rom. 12:1; 1 Cor. 6:20). Just as God raised Jesus Christ, so Christians await a resurrection of their own bodies, Christ being the "first fruits" of the new creation (1 Cor. 15:20). Ultimately, this is their hope—that God has begun His work of "making all things new" in the work of Jesus Christ and in the continued sanctification of His saints (Rev. 21:5). They await the new heavens and new earth in which there will be no more sin, pain, or sorrow (Rev. 21:4).',
];

export default data;
